### ISSUE TITLE
Suggested readings

### ISSUE THREAD

**Issue by skanderm** [pmiller10/cambridge-ai#2]
Hi group, I came across this list of curated papers from which we might want to read:

https://github.com/songrotek/Deep-Learning-Papers-Reading-Roadmap

The list looks like a fairly high-level survey of applications (Vision, Speech, Optimization, etc.). Personally, I'd be interested in going over these:

Amodei, Dario, et al. "**Deep speech 2: End-to-end speech recognition in english and mandarin.**" arXiv preprint arXiv:1512.02595 (2015). [[pdf]](https://arxiv.org/pdf/1512.02595.pdf) **(Baidu Speech Recognition System)**

van den Oord, Aaron, et al. "**WaveNet: A Generative Model for Raw Audio**" arXiv preprint arXiv:1609.03499v2 (2016). [[pdf]](https://arxiv.org/pdf/1609.03499v2.pdf) [[blog]](https://deepmind.com/blog/wavenet-generative-model-raw-audio/) [[code]](https://github.com/ibab/tensorflow-wavenet) **(Google DeepMind Generative Speech)**

**Comment by pmiller10** [comment]
Sounds good, want me to add those 2 papers to the suggested list?
